name: Black Duck SCA Build Scan

on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]

jobs:
  blackduck-scan:
    runs-on: [ self-hosted ]
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Specify Node version
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm install  

    - name: Build Project
      run: |
        npm rebuild

    - name: Black Duck SCA Build Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        detect_args: "--detect.source.path=${{ github.workspace }}"
        
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
